# Generated by Django 3.1.1 on 2020-12-17 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exevada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelanalysis',
            name='seasonal_cycle',
        ),
        migrations.RemoveField(
            model_name='modelanalysis',
            name='spatial_pattern',
        ),
        migrations.RemoveField(
            model_name='modelanalysis',
            name='trend',
        ),
        migrations.RemoveField(
            model_name='observationanalysis',
            name='trend',
        ),
        migrations.AddField(
            model_name='attribution',
            name='research_data',
            field=models.URLField(blank=True, help_text='Research material and data location', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='research_data_doi',
            field=models.CharField(blank=True, help_text='DOI (no URL) of research data', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='atrribution_consideration_statement',
            field=models.TextField(blank=True, help_text='Reason why no attribution studies have been done', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='environmental_impact',
            field=models.TextField(blank=True, default='', help_text='Environmental impact', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='socio_economic_impact',
            field=models.TextField(blank=True, default='', help_text='Socio-economic impact', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='comments',
            field=models.TextField(blank=True, help_text='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='deaths',
            field=models.PositiveIntegerField(blank=True, help_text='Number of casualties', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='economical_loss',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated economic loss (in million euro)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='people_affected',
            field=models.PositiveIntegerField(blank=True, help_text='Number (million) of people affected', null=True),
        ),
        migrations.CreateModel(
            name='ImpactResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Event impact source location url', max_length=512)),
                ('doi', models.CharField(blank=True, help_text='DOI (no URL) of impact resource', max_length=256, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_resources', to='exevada.event')),
            ],
        ),
    ]
