# Generated by Django 3.1.1 on 2021-04-14 17:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exevada', '0002_auto_20201217_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='atrribution_consideration_statement',
            new_name='attribution_consideration_statement',
        ),
        migrations.AlterField(
            model_name='attribution',
            name='Delta_I',
            field=models.FloatField(blank=True, help_text='Intensity change', null=True),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='Delta_I_max',
            field=models.FloatField(blank=True, help_text='Intensity change upper bound', null=True),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='Delta_I_min',
            field=models.FloatField(blank=True, help_text='Intensity change lower bound', null=True),
        ),
        migrations.AlterField(
            model_name='attribution',
            name='PR',
            field=models.FloatField(blank=True, help_text='Probability ratio', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='modelanalysis',
            name='Delta_I',
            field=models.FloatField(blank=True, help_text='Intensity change', null=True),
        ),
        migrations.AlterField(
            model_name='modelanalysis',
            name='Delta_I_max',
            field=models.FloatField(blank=True, help_text='Intensity change upper bound', null=True),
        ),
        migrations.AlterField(
            model_name='modelanalysis',
            name='Delta_I_min',
            field=models.FloatField(blank=True, help_text='Intensity change lower bound', null=True),
        ),
        migrations.AlterField(
            model_name='modelanalysis',
            name='PR',
            field=models.FloatField(blank=True, help_text='Probability ratio', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='modelanalysis',
            name='dataset',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exevada.modeldataset'),
        ),
        migrations.AlterField(
            model_name='modeldataset',
            name='experiment',
            field=models.CharField(blank=True, help_text='Experiment', max_length=512),
        ),
        migrations.AlterField(
            model_name='modeldataset',
            name='model_name',
            field=models.CharField(help_text='Model output dataset', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='observationanalysis',
            name='Delta_I',
            field=models.FloatField(blank=True, help_text='Intensity change', null=True),
        ),
        migrations.AlterField(
            model_name='observationanalysis',
            name='Delta_I_max',
            field=models.FloatField(blank=True, help_text='Intensity change upper bound', null=True),
        ),
        migrations.AlterField(
            model_name='observationanalysis',
            name='Delta_I_min',
            field=models.FloatField(blank=True, help_text='Intensity change lower bound', null=True),
        ),
        migrations.AlterField(
            model_name='observationanalysis',
            name='PR',
            field=models.FloatField(blank=True, help_text='Probability ratio', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='observationanalysis',
            name='T_return',
            field=models.PositiveIntegerField(blank=True, help_text='Return period (yr)', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='observationanalysis',
            name='dataset',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exevada.observationdataset'),
        ),
        migrations.AlterField(
            model_name='observationdataset',
            name='name',
            field=models.CharField(help_text='Observation dataset', max_length=256, unique=True),
        ),
    ]
